/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joao
 */
public class AddPiano extends javax.swing.JFrame {

    /**
     * Creates new form AddCustumer
     */
    
    private Storage storage = Storage.createStorage();
    
    private static AddPiano a;
    
    private AddPiano() {
        initComponents();
    }
    
    public static AddPiano createAddPiano() {
        if(a == null) {
            a = new AddPiano();
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        modelLb = new javax.swing.JLabel();
        brandLb = new javax.swing.JLabel();
        bodyLb = new javax.swing.JLabel();
        typeLb = new javax.swing.JLabel();
        keyLb = new javax.swing.JLabel();
        priceLb = new javax.swing.JLabel();
        modelTf = new javax.swing.JTextField();
        brandTf = new javax.swing.JTextField();
        bodyTf = new javax.swing.JTextField();
        typeTf = new javax.swing.JTextField();
        keyTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        registerBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("REGISTER PIANO");

        modelLb.setText("Model:");

        brandLb.setText("Brand:");

        bodyLb.setText("Body Type:");

        typeLb.setText("Type:");

        keyLb.setText("Key count:");

        priceLb.setText("Price:");

        modelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTfActionPerformed(evt);
            }
        });

        bodyTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTfActionPerformed(evt);
            }
        });

        typeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTfActionPerformed(evt);
            }
        });

        keyTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyTfActionPerformed(evt);
            }
        });

        priceTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTfActionPerformed(evt);
            }
        });

        closeBt.setText("Close");

        registerBt.setText("Register");
        registerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerBt)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLb)
                            .addComponent(brandLb)
                            .addComponent(bodyLb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(brandTf)
                            .addComponent(bodyTf, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(modelTf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyLb)
                            .addComponent(typeLb)
                            .addComponent(priceLb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTf)
                            .addComponent(keyTf)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(typeTf)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleTf)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLb)
                    .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLb)
                    .addComponent(brandTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyLb)
                    .addComponent(bodyTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLb)
                    .addComponent(typeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyLb)
                    .addComponent(keyTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLb)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTfActionPerformed

    private void registerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtActionPerformed
        registerPiano();
        modelTf.setText("");
        brandTf.setText("");
        bodyTf.setText("");
        typeTf.setText("");
        keyTf.setText("");
        priceTf.setText("");
    }//GEN-LAST:event_registerBtActionPerformed

    private void priceTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTfActionPerformed

    private void keyTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyTfActionPerformed

    private void typeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTfActionPerformed

    private void bodyTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyTfActionPerformed

    private void registerPiano() {
        Piano p = new Piano();
        p.setModel(modelTf.getText());
        p.setBrand(brandTf.getText());
        p.setBodyType(bodyTf.getText());
        p.setType(typeTf.getText());
        p.setKeyCount(Integer.parseInt(keyTf.getText()));
        p.setPrice(Float.parseFloat(priceTf.getText()));
        p.setCategory("Keys");
        storage.getPianoStock().add(p);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPiano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bodyLb;
    private javax.swing.JTextField bodyTf;
    private javax.swing.JLabel brandLb;
    private javax.swing.JTextField brandTf;
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel keyLb;
    private javax.swing.JTextField keyTf;
    private javax.swing.JLabel modelLb;
    private javax.swing.JTextField modelTf;
    private javax.swing.JLabel priceLb;
    private javax.swing.JTextField priceTf;
    private javax.swing.JButton registerBt;
    private javax.swing.JLabel titleTf;
    private javax.swing.JLabel typeLb;
    private javax.swing.JTextField typeTf;
    // End of variables declaration//GEN-END:variables
}
