/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joao
 */
public class FormEditAcquisition extends javax.swing.JFrame {

    /**
     * Creates new form FormEditCustomer
     */
    
    private BDStorage storage = BDStorage.createStorage();
    
    private static FormEditAcquisition e;
    
    private FormEditAcquisition() {
        initComponents();
    }

    public static FormEditAcquisition createEditAcquisition() {
        if(e == null) {
            e = new FormEditAcquisition();
        }
        return e;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        closeBt = new javax.swing.JButton();
        saveBt = new javax.swing.JButton();
        idLb = new javax.swing.JLabel();
        idTf = new javax.swing.JTextField();
        newLb = new javax.swing.JLabel();
        employeeCpfLb = new javax.swing.JLabel();
        customerCpfLb = new javax.swing.JLabel();
        prodAmountLb = new javax.swing.JLabel();
        modelTf = new javax.swing.JTextField();
        employeeCpfTf = new javax.swing.JTextField();
        custumerCpfTf = new javax.swing.JTextField();
        productAmountTf = new javax.swing.JTextField();
        modelLb = new javax.swing.JLabel();
        instrumentCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Acquisition");

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("EDIT ACQUISITION");

        closeBt.setText("Close");

        saveBt.setText("Save");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        idLb.setText("Acquisition ID: ");

        idTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTfActionPerformed(evt);
            }
        });

        newLb.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        newLb.setText("New Information (Leave blank for no changes):");

        employeeCpfLb.setText("Employee CPF:");

        customerCpfLb.setText("Customer CPF:");

        prodAmountLb.setText("Product Amount:");

        modelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTfActionPerformed(evt);
            }
        });

        custumerCpfTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custumerCpfTfActionPerformed(evt);
            }
        });

        productAmountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAmountTfActionPerformed(evt);
            }
        });

        modelLb.setText("Instrument Model:");

        instrumentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guitar", "Piano", "Drums" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBt))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idTf))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newLb)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modelLb)
                                            .addComponent(employeeCpfLb)
                                            .addComponent(customerCpfLb)
                                            .addComponent(prodAmountLb))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(employeeCpfTf, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(custumerCpfTf, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(productAmountTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(instrumentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleTf)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLb)
                    .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(newLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLb)
                    .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeCpfLb)
                    .addComponent(employeeCpfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerCpfLb)
                    .addComponent(custumerCpfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodAmountLb)
                    .addComponent(productAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBt)
                    .addComponent(closeBt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTfActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        editAcquisition();
    }//GEN-LAST:event_saveBtActionPerformed

    private void modelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTfActionPerformed

    private void custumerCpfTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custumerCpfTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custumerCpfTfActionPerformed

    private void productAmountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAmountTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productAmountTfActionPerformed

    private void cleanTf() {
        idTf.setText("");
        modelTf.setText("");
        employeeCpfTf.setText("");
        custumerCpfTf.setText("");
        productAmountTf.setText("");
    }
    
    private void editAcquisition() {
        int id = 0;
        
        try {   
            id = GetArrayId.createGetArrayId().getSaleId(InputExeptionHandler.createInputExeptionHandler().InputInt(idTf.getText()));
            
            Acquisition a = storage.getAcquisitions().get(id);
            
            a.setProductAmount(InputExeptionHandler.createInputExeptionHandler().InputInt(productAmountTf.getText()));

            a.setProductType(instrumentCb.getSelectedItem().toString());

            switch(instrumentCb.getSelectedItem().toString()) {
                case "Guitar":
                    id = GetArrayId.createGetArrayId().getGuitarId(modelTf.getText());
                    a.setProduct(storage.getGuitarStock().get(id));
                    break;
                case "Piano":
                    id = GetArrayId.createGetArrayId().getPianoId(modelTf.getText());
                    a.setProduct(storage.getPianoStock().get(id));
                    break;
                case "Drums":
                    id = GetArrayId.createGetArrayId().getDrumsId(modelTf.getText());
                    a.setProduct(storage.getDrumsStock().get(id));
                    break;
            }

            id = GetArrayId.createGetArrayId().getEmployeeId(employeeCpfTf.getText());
            a.setInCharge(storage.getEmployees().get(id));

            a.setTotalCost(a.getProduct().getPrice() * a.getProductAmount());

            a.setDate("fix");

            a.getProduct().setAvailability(a.getProduct().getAvailability() - a.getProductAmount());    
            
            storage.getAcquisitions().set(id, a);
            
            cleanTf();
        }
        catch(IntInputErrorException iee) {
            iee.intErr("id, product amount");
        }
        catch(ItemNotFoundExeption infe) {
            infe.itemNotFoundErr();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditAcquisition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel customerCpfLb;
    private javax.swing.JTextField custumerCpfTf;
    private javax.swing.JLabel employeeCpfLb;
    private javax.swing.JTextField employeeCpfTf;
    private javax.swing.JLabel idLb;
    private javax.swing.JTextField idTf;
    private javax.swing.JComboBox<String> instrumentCb;
    private javax.swing.JLabel modelLb;
    private javax.swing.JTextField modelTf;
    private javax.swing.JLabel newLb;
    private javax.swing.JLabel prodAmountLb;
    private javax.swing.JTextField productAmountTf;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel titleTf;
    // End of variables declaration//GEN-END:variables
}
