/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joao
 */
public class FormAddDrums extends javax.swing.JFrame {

    /**
     * Creates new form FormAddCustumer
     */
    
    private BDStorage storage = BDStorage.createStorage();
    
    private static FormAddDrums a;
    
    private FormAddDrums() {
        initComponents();
    }
    
    public static FormAddDrums createAddDrums() {
        if(a == null) {
            a = new FormAddDrums();
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        modelLb = new javax.swing.JLabel();
        brandLb = new javax.swing.JLabel();
        shellLb = new javax.swing.JLabel();
        typeLb = new javax.swing.JLabel();
        piecesLb = new javax.swing.JLabel();
        priceLb = new javax.swing.JLabel();
        modelTf = new javax.swing.JTextField();
        brandTf = new javax.swing.JTextField();
        shellTf = new javax.swing.JTextField();
        typeTf = new javax.swing.JTextField();
        piecesTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        registerBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("REGISTER DRUMS");

        modelLb.setText("Model:");

        brandLb.setText("Brand:");

        shellLb.setText("Shell Material:");

        typeLb.setText("Type:");

        piecesLb.setText("Pieces Count:");

        priceLb.setText("Price:");

        modelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTfActionPerformed(evt);
            }
        });

        shellTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shellTfActionPerformed(evt);
            }
        });

        typeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTfActionPerformed(evt);
            }
        });

        piecesTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piecesTfActionPerformed(evt);
            }
        });

        priceTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTfActionPerformed(evt);
            }
        });

        closeBt.setText("Close");

        registerBt.setText("Register");
        registerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerBt)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLb)
                            .addComponent(brandLb)
                            .addComponent(shellLb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(brandTf)
                            .addComponent(shellTf, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(modelTf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piecesLb)
                            .addComponent(typeLb)
                            .addComponent(priceLb))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piecesTf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeTf)
                            .addComponent(priceTf))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleTf)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLb)
                    .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLb)
                    .addComponent(brandTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shellLb)
                    .addComponent(shellTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLb)
                    .addComponent(typeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piecesLb)
                    .addComponent(piecesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLb)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTfActionPerformed

    private void registerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtActionPerformed
        registerDrums();
        modelTf.setText("");
        brandTf.setText("");
        shellTf.setText("");
        typeTf.setText("");
        piecesTf.setText("");
        priceTf.setText("");
    }//GEN-LAST:event_registerBtActionPerformed

    private void priceTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTfActionPerformed

    private void piecesTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piecesTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piecesTfActionPerformed

    private void typeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTfActionPerformed

    private void shellTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shellTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shellTfActionPerformed

    private void registerDrums() {
        Drums d = new Drums();
        try {
            d.setModel(modelTf.getText());
            d.setBrand(brandTf.getText());
            d.setShellMaterial(shellTf.getText());
            d.setType(typeTf.getText());
            d.setPiecesCount(InputExeptionHandler.createInputExeptionHandler().InputInt(piecesTf.getText()));
            d.setPrice(InputExeptionHandler.createInputExeptionHandler().InputFloat(priceTf.getText()));
            d.setCategory("Percussion");
            storage.getDrumsStock().add(d);
        }
        catch(InputErrorException iee) {
            iee.intErr();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddDrums().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandLb;
    private javax.swing.JTextField brandTf;
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel modelLb;
    private javax.swing.JTextField modelTf;
    private javax.swing.JLabel piecesLb;
    private javax.swing.JTextField piecesTf;
    private javax.swing.JLabel priceLb;
    private javax.swing.JTextField priceTf;
    private javax.swing.JButton registerBt;
    private javax.swing.JLabel shellLb;
    private javax.swing.JTextField shellTf;
    private javax.swing.JLabel titleTf;
    private javax.swing.JLabel typeLb;
    private javax.swing.JTextField typeTf;
    // End of variables declaration//GEN-END:variables
}
