//João Alberto Benaci Torezan

import javax.swing.JOptionPane;

public class FormEditDrums extends javax.swing.JFrame {

    /**
     * Creates new form FormEditCustomer
     */
    
    private BDStorage storage = BDStorage.createStorage();
    
    private InputExceptionHandler ieh = InputExceptionHandler.createInputExeptionHandler();
    
    private static FormEditDrums e;
    
    private FormEditDrums() {
        initComponents();
    }

    //MÉTODO SINGLETON
    
    public static FormEditDrums createEditDrums() {
        if(e == null) {
            e = new FormEditDrums();
        }
        return e;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        brandTf = new javax.swing.JTextField();
        brandLb = new javax.swing.JLabel();
        newModelLb = new javax.swing.JLabel();
        NewModelTf = new javax.swing.JTextField();
        shellLb = new javax.swing.JLabel();
        shellTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        saveBt = new javax.swing.JButton();
        registeredLb = new javax.swing.JLabel();
        registeredModelLb = new javax.swing.JLabel();
        registeredModelTf = new javax.swing.JTextField();
        newLb = new javax.swing.JLabel();
        piecesLb = new javax.swing.JLabel();
        piecesTf = new javax.swing.JTextField();
        typeTf = new javax.swing.JTextField();
        typeLb = new javax.swing.JLabel();
        priceTf = new javax.swing.JTextField();
        priceLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Drums");

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("EDIT DRUMS");

        brandTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTfActionPerformed(evt);
            }
        });

        brandLb.setText("Brand:");

        newModelLb.setText("Model:");

        NewModelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewModelTfActionPerformed(evt);
            }
        });

        shellLb.setText("Shell Material:");

        closeBt.setText("Close");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });

        saveBt.setText("Save");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        registeredLb.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        registeredLb.setText("Registered Model:");

        registeredModelLb.setText("Model:");

        registeredModelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredModelTfActionPerformed(evt);
            }
        });

        newLb.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        newLb.setText("New Information (Leave blank for no changes):");

        piecesLb.setText("Pieces Count:");

        typeLb.setText("Type:");

        priceLb.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registeredModelLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registeredModelTf))
                    .addComponent(newLb)
                    .addComponent(registeredLb)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLb)
                            .addComponent(shellLb)
                            .addComponent(newModelLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandTf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(shellTf)
                            .addComponent(NewModelTf)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piecesLb)
                            .addComponent(typeLb)
                            .addComponent(priceLb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTf)
                            .addComponent(typeTf)
                            .addComponent(piecesTf, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleTf)
                .addGap(18, 18, 18)
                .addComponent(registeredLb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registeredModelLb)
                    .addComponent(registeredModelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(newLb)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newModelLb)
                    .addComponent(NewModelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLb)
                    .addComponent(brandTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shellLb)
                    .addComponent(shellTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLb)
                    .addComponent(typeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piecesLb)
                    .addComponent(piecesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLb)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brandTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTfActionPerformed

    private void NewModelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewModelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewModelTfActionPerformed

    private void registeredModelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredModelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredModelTfActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        editDrums();
    }//GEN-LAST:event_saveBtActionPerformed

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        exit();
    }//GEN-LAST:event_closeBtActionPerformed

    private void cleanTf() {
        brandTf.setText("");
        registeredModelTf.setText("");
        shellTf.setText("");
        NewModelTf.setText("");
        piecesTf.setText("");
        priceTf.setText("");
        typeTf.setText("");
    }
    
    private void editDrums() {
        try {   
            int id = GetArrayId.createGetArrayId().getDrumsId(registeredModelTf.getText());
            storage.getDrumsStock().get(id).setPiecesCount(ieh.InputInt(piecesTf.getText())); //Reflexividade
            storage.getDrumsStock().get(id).setPrice(ieh.InputFloat(priceTf.getText())); //Reflexividade
            storage.getDrumsStock().get(id).setModel(NewModelTf.getText()); //Reflexividade
            storage.getDrumsStock().get(id).setBrand(brandTf.getText()); //Reflexividade
            storage.getDrumsStock().get(id).setShellMaterial(shellTf.getText()); //Reflexividade
            storage.getDrumsStock().get(id).setType(typeTf.getText()); //Reflexividade
            
            cleanTf();
        }
        catch(IntInputErrorException iee) {
            iee.intErr("pieces count");
        }
        catch(FloatInputErrorException fiee) {
            fiee.floatErr("price");
        }
        catch(ItemNotFoundExeption infe) {
            infe.itemNotFoundErr();
        }
        catch(ShellMaterialException sme) {
            sme.shellMaterialErr();
        }
    }
    
    public void exit(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Do you really want to exit?",
                "Exit",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){
           dispose();
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditDrums().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewModelTf;
    private javax.swing.JLabel brandLb;
    private javax.swing.JTextField brandTf;
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel newLb;
    private javax.swing.JLabel newModelLb;
    private javax.swing.JLabel piecesLb;
    private javax.swing.JTextField piecesTf;
    private javax.swing.JLabel priceLb;
    private javax.swing.JTextField priceTf;
    private javax.swing.JLabel registeredLb;
    private javax.swing.JLabel registeredModelLb;
    private javax.swing.JTextField registeredModelTf;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel shellLb;
    private javax.swing.JTextField shellTf;
    private javax.swing.JLabel titleTf;
    private javax.swing.JLabel typeLb;
    private javax.swing.JTextField typeTf;
    // End of variables declaration//GEN-END:variables
}
