//João Alberto Benaci Torezan

import javax.swing.JOptionPane;

public class FormAddAcquisition extends javax.swing.JFrame {

    /**
     * Creates new form FormAddCustomer
     */
    
    private BDStorage storage = BDStorage.createStorage();
    
    private GetArrayId garrid = GetArrayId.createGetArrayId();
    
    private static FormAddAcquisition a;
    
    private FormAddAcquisition() {
        initComponents();
    }
    
    //MÉTODO SINGLETON
    
    public static FormAddAcquisition createAddAcquisition() {
        if(a == null) {
            a = new FormAddAcquisition();
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        modelLb = new javax.swing.JLabel();
        employeeCpfLb = new javax.swing.JLabel();
        supplyerLb = new javax.swing.JLabel();
        prodAmountLb = new javax.swing.JLabel();
        modelTf = new javax.swing.JTextField();
        supplyerTf = new javax.swing.JTextField();
        custumerCpfTf = new javax.swing.JTextField();
        productAmountTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        registerBt = new javax.swing.JButton();
        instrumentCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Acquisition");

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("REGISTER ACQUISITION");

        modelLb.setText("Instrument Model:");

        employeeCpfLb.setText("Employee CPF:");

        supplyerLb.setText("Supplyer Name:");

        prodAmountLb.setText("Product Amount:");

        modelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTfActionPerformed(evt);
            }
        });

        custumerCpfTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custumerCpfTfActionPerformed(evt);
            }
        });

        productAmountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAmountTfActionPerformed(evt);
            }
        });

        closeBt.setText("Close");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });

        registerBt.setText("Register");
        registerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtActionPerformed(evt);
            }
        });

        instrumentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guitar", "Piano", "Drums" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerBt)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelLb)
                    .addComponent(employeeCpfLb)
                    .addComponent(supplyerLb)
                    .addComponent(prodAmountLb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(instrumentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(supplyerTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(custumerCpfTf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(productAmountTf, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleTf)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLb)
                    .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeCpfLb)
                    .addComponent(supplyerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplyerLb)
                    .addComponent(custumerCpfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodAmountLb)
                    .addComponent(productAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTfActionPerformed

    private void registerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtActionPerformed
        registerAcquisition();
    }//GEN-LAST:event_registerBtActionPerformed

    private void productAmountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAmountTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productAmountTfActionPerformed

    private void custumerCpfTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custumerCpfTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custumerCpfTfActionPerformed

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        exit();
    }//GEN-LAST:event_closeBtActionPerformed

    private void cleanTf() {
        modelTf.setText("");
        supplyerTf.setText("");
        custumerCpfTf.setText("");
        productAmountTf.setText("");
    }
    
    private void registerAcquisition() {
        Acquisition a = new Acquisition();
        int id = 0;
        
        try {
            a.setProductType(instrumentCb.getSelectedItem().toString());

            switch(instrumentCb.getSelectedItem().toString()) {
                case "Guitar":
                    id = garrid.getGuitarId(modelTf.getText());
                    a.setProduct(storage.getGuitarStock().get(id)); //Reflexividade
                    break;
                case "Piano":
                    id = garrid.getPianoId(modelTf.getText());
                    a.setProduct(storage.getPianoStock().get(id)); //Reflexividade
                    break;
                case "Drums":
                    id = garrid.getDrumsId(modelTf.getText());
                    a.setProduct(storage.getDrumsStock().get(id)); //Reflexividade
                    break;
            }

            id = garrid.getEmployeeId(supplyerTf.getText());
            a.setInCharge(storage.getEmployees().get(id)); //Reflexividade
            a.setProductAmount(InputExceptionHandler.createInputExeptionHandler().InputInt(productAmountTf.getText()));
            
            a.setTotalCost(a.getProduct().getPrice() * a.getProductAmount()); //Reflexividade
            
            a.setDate(GetDate.createGetDate().getDate()); //Reflexividade

            storage.setAcquisitionIds(storage.getAcquisitionIds() + 1);
            a.setOpId(storage.getAcquisitionIds());

            a.getProduct().setAvailability(a.getProduct().getAvailability() + a.getProductAmount());  //Reflexividade

            storage.getAcquisitions().add(a); //Reflexividade
            
            cleanTf();
        }
        catch(IntInputErrorException iee) {
            iee.intErr("product amount");
        }
        catch(ItemNotFoundExeption infe) {
            infe.itemNotFoundErr();
        } 
    }
    
    public void exit(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Do you really want to exit?",
                "Exit",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){
           dispose();
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddAcquisition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBt;
    private javax.swing.JTextField custumerCpfTf;
    private javax.swing.JLabel employeeCpfLb;
    private javax.swing.JComboBox<String> instrumentCb;
    private javax.swing.JLabel modelLb;
    private javax.swing.JTextField modelTf;
    private javax.swing.JLabel prodAmountLb;
    private javax.swing.JTextField productAmountTf;
    private javax.swing.JButton registerBt;
    private javax.swing.JLabel supplyerLb;
    private javax.swing.JTextField supplyerTf;
    private javax.swing.JLabel titleTf;
    // End of variables declaration//GEN-END:variables
}
