/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joao
 */
public class AddSale extends javax.swing.JFrame {

    /**
     * Creates new form AddCustumer
     */
    
    private Storage storage = Storage.createStorage();
    
    private static AddSale a;
    
    private AddSale() {
        initComponents();
    }
    
    public static AddSale createAddSale() {
        if(a == null) {
            a = new AddSale();
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        modelLb = new javax.swing.JLabel();
        employeeCpfLb = new javax.swing.JLabel();
        custumerCpfLb = new javax.swing.JLabel();
        prodAmountLb = new javax.swing.JLabel();
        modelTf = new javax.swing.JTextField();
        employeeCpfTf = new javax.swing.JTextField();
        custumerCpfTf = new javax.swing.JTextField();
        productAmountTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        registerBt = new javax.swing.JButton();
        instrumentCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("REGISTER SALE");

        modelLb.setText("Instrument Model:");

        employeeCpfLb.setText("Employee CPF:");

        custumerCpfLb.setText("Custumer CPF:");

        prodAmountLb.setText("Product Amount:");

        modelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTfActionPerformed(evt);
            }
        });

        custumerCpfTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custumerCpfTfActionPerformed(evt);
            }
        });

        productAmountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAmountTfActionPerformed(evt);
            }
        });

        closeBt.setText("Close");

        registerBt.setText("Register");
        registerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtActionPerformed(evt);
            }
        });

        instrumentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guitar", "Piano", "Drums" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerBt)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelLb)
                    .addComponent(employeeCpfLb)
                    .addComponent(custumerCpfLb)
                    .addComponent(prodAmountLb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(instrumentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(employeeCpfTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(custumerCpfTf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(productAmountTf, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleTf)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLb)
                    .addComponent(modelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeCpfLb)
                    .addComponent(employeeCpfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custumerCpfLb)
                    .addComponent(custumerCpfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodAmountLb)
                    .addComponent(productAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTfActionPerformed

    private void registerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtActionPerformed
        registerSale();
        modelTf.setText("");
        employeeCpfTf.setText("");
        custumerCpfTf.setText("");
        productAmountTf.setText("");
    }//GEN-LAST:event_registerBtActionPerformed

    private void productAmountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAmountTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productAmountTfActionPerformed

    private void custumerCpfTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custumerCpfTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custumerCpfTfActionPerformed

    private void registerSale() {
        Sale s = new Sale();
        int id = 0;
        
        s.setProductType(instrumentCb.getSelectedItem().toString());
        
        switch(instrumentCb.getSelectedItem().toString()) {
            case "Guitar":
                id = GetArrayId.createGetArrayId().getGuitarId(modelTf.getText());
                s.setProduct(storage.getGuitarStock().get(id));
                break;
            case "Piano":
                id = GetArrayId.createGetArrayId().getPianoId(modelTf.getText());
                s.setProduct(storage.getPianoStock().get(id));
                break;
            case "Drums":
                id = GetArrayId.createGetArrayId().getDrumsId(modelTf.getText());
                s.setProduct(storage.getDrumsStock().get(id));
                break;
        }
        
        id = GetArrayId.createGetArrayId().getEmployeeId(employeeCpfTf.getText());
        s.setInCharge(storage.getEmployees().get(id));
        
        id = GetArrayId.createGetArrayId().getCustumerId(custumerCpfTf.getText());
        s.setBuyer(storage.getCustomers().get(id));
        
        s.setProductAmount(Integer.parseInt(productAmountTf.getText()));
        
        s.setTotalCost(s.getProduct().getPrice() * s.getProductAmount());
        
        s.setDate("fix");
        
        storage.setSaleIds(storage.getSaleIds() + 1);
        s.setOpId(storage.getSaleIds());
        
        s.getBuyer().setPurchaseCount(s.getBuyer().getPurchaseCount() + 1);
        s.getProduct().setAvailability(s.getProduct().getAvailability() - s.getProductAmount()); 
        
        storage.getSales().add(s);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel custumerCpfLb;
    private javax.swing.JTextField custumerCpfTf;
    private javax.swing.JLabel employeeCpfLb;
    private javax.swing.JTextField employeeCpfTf;
    private javax.swing.JComboBox<String> instrumentCb;
    private javax.swing.JLabel modelLb;
    private javax.swing.JTextField modelTf;
    private javax.swing.JLabel prodAmountLb;
    private javax.swing.JTextField productAmountTf;
    private javax.swing.JButton registerBt;
    private javax.swing.JLabel titleTf;
    // End of variables declaration//GEN-END:variables
}
