/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joao
 */
public class FormEditPiano extends javax.swing.JFrame {

    /**
     * Creates new form FormEditCustomer
     */
    
    private BDStorage storage = BDStorage.createStorage();
    
    private static FormEditPiano e;
    
    private FormEditPiano() {
        initComponents();
    }

    public static FormEditPiano createEditPiano() {
        if(e == null) {
            e = new FormEditPiano();
        }
        return e;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        brandTf = new javax.swing.JTextField();
        brandLb = new javax.swing.JLabel();
        newModelLb = new javax.swing.JLabel();
        NewModelTf = new javax.swing.JTextField();
        bodyLb = new javax.swing.JLabel();
        bodyTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        saveBt = new javax.swing.JButton();
        registeredLb = new javax.swing.JLabel();
        registeredModelLb = new javax.swing.JLabel();
        registeredModelTf = new javax.swing.JTextField();
        newLb = new javax.swing.JLabel();
        keyLb = new javax.swing.JLabel();
        keyTf = new javax.swing.JTextField();
        typeTf = new javax.swing.JTextField();
        typeLb = new javax.swing.JLabel();
        priceTf = new javax.swing.JTextField();
        priceLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Piano");

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("EDIT PIANO");

        brandTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTfActionPerformed(evt);
            }
        });

        brandLb.setText("Brand:");

        newModelLb.setText("Model:");

        NewModelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewModelTfActionPerformed(evt);
            }
        });

        bodyLb.setText("Body Type:");

        closeBt.setText("Close");

        saveBt.setText("Save");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        registeredLb.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        registeredLb.setText("Registered Model:");

        registeredModelLb.setText("Model:");

        registeredModelTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredModelTfActionPerformed(evt);
            }
        });

        newLb.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        newLb.setText("New Information (Leave blank for no changes):");

        keyLb.setText("Key Count:");

        typeLb.setText("Type:");

        priceLb.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registeredModelLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registeredModelTf))
                    .addComponent(newLb)
                    .addComponent(registeredLb)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLb)
                            .addComponent(bodyLb)
                            .addComponent(newModelLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandTf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bodyTf)
                            .addComponent(NewModelTf)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyLb)
                            .addComponent(typeLb)
                            .addComponent(priceLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTf)
                            .addComponent(typeTf)
                            .addComponent(keyTf, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleTf)
                .addGap(18, 18, 18)
                .addComponent(registeredLb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registeredModelLb)
                    .addComponent(registeredModelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(newLb)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newModelLb)
                    .addComponent(NewModelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLb)
                    .addComponent(brandTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyLb)
                    .addComponent(bodyTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLb)
                    .addComponent(typeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyLb)
                    .addComponent(keyTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLb)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brandTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTfActionPerformed

    private void NewModelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewModelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewModelTfActionPerformed

    private void registeredModelTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredModelTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredModelTfActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        editPiano();
    }//GEN-LAST:event_saveBtActionPerformed

    private void cleanTf() {
        brandTf.setText("");
        registeredModelTf.setText("");
        bodyTf.setText("");
        NewModelTf.setText("");
        keyTf.setText("");
        priceTf.setText("");
        typeTf.setText("");
    }
    
    private void editPiano() {
        try {
            int id = GetArrayId.createGetArrayId().getPianoId(registeredModelTf.getText());
            storage.getPianoStock().get(id).setKeyCount(InputExceptionHandler.createInputExeptionHandler().InputInt(keyTf.getText()));
            storage.getPianoStock().get(id).setPrice(InputExceptionHandler.createInputExeptionHandler().InputFloat(priceTf.getText()));
            storage.getPianoStock().get(id).setModel(NewModelTf.getText());
            storage.getPianoStock().get(id).setBrand(brandTf.getText());
            storage.getPianoStock().get(id).setBodyType(bodyTf.getText());
            storage.getPianoStock().get(id).setType(typeTf.getText());
            
            cleanTf();
        }
        catch(IntInputErrorException iee) {
            iee.intErr("key count");
        }
        catch(FloatInputErrorException fiee) {
            fiee.floatErr("price");
        }
        catch(ItemNotFoundExeption infe) {
            infe.itemNotFoundErr();
        }
        catch(KeyCountException kce) {
            kce.keyCountErr();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditPiano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewModelTf;
    private javax.swing.JLabel bodyLb;
    private javax.swing.JTextField bodyTf;
    private javax.swing.JLabel brandLb;
    private javax.swing.JTextField brandTf;
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel keyLb;
    private javax.swing.JTextField keyTf;
    private javax.swing.JLabel newLb;
    private javax.swing.JLabel newModelLb;
    private javax.swing.JLabel priceLb;
    private javax.swing.JTextField priceTf;
    private javax.swing.JLabel registeredLb;
    private javax.swing.JLabel registeredModelLb;
    private javax.swing.JTextField registeredModelTf;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel titleTf;
    private javax.swing.JLabel typeLb;
    private javax.swing.JTextField typeTf;
    // End of variables declaration//GEN-END:variables
}
