//João Alberto Benaci Torezan

import javax.swing.JOptionPane;

public class FormDelOperation extends javax.swing.JFrame {

    /**
     * Creates new form FormDelPeople
     */
    
    private BDStorage storage = BDStorage.createStorage();
    
    private GetArrayId garrid = GetArrayId.createGetArrayId();
    
    private InputExceptionHandler ieh = InputExceptionHandler.createInputExeptionHandler();
    
    private static FormDelOperation d;
    
    private FormDelOperation() {
        initComponents();
    }

    //MÉTODO SINGLETON
    
    public static FormDelOperation createDelOperation() {
        if(d == null) {
            d = new FormDelOperation();
        }
        return d;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        opLb = new javax.swing.JLabel();
        opTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        removeBt = new javax.swing.JButton();
        opCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Operation");

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("REMOVE OPERATION");

        opLb.setText("Operation ID:");

        opTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opTfActionPerformed(evt);
            }
        });

        closeBt.setText("Close");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });

        removeBt.setText("Remove");
        removeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtActionPerformed(evt);
            }
        });

        opCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sale", "Acquisition" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(closeBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeBt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opTf, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleTf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opLb)
                    .addComponent(opTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeOperation() {
        int id = 0;
        
        try{
            if(opCb.getSelectedItem().toString().equals("Sale")) {
                id = garrid.getSaleId(ieh.InputInt(opTf.getText()));
                Instrument i = storage.getSales().get(id).getProduct(); //Reflexividade
                i.setAvailability(i.getAvailability() + storage.getSales().get(id).getProductAmount()); 
                storage.getSales().remove(id); //Reflexividade
            }
            else {
                id = garrid.getAcquisitionId(ieh.InputInt(opTf.getText()));
                Instrument i = storage.getAcquisitions().get(id).getProduct(); //Reflexividade
                i.setAvailability(i.getAvailability() + storage.getAcquisitions().get(id).getProductAmount()); 
                storage.getAcquisitions().remove(id); //Reflexividade
            }
            
            opTf.setText("");
        }
        catch(IntInputErrorException iee) {
            iee.intErr("id");
        }
        catch(ItemNotFoundExeption infe) {
            infe.itemNotFoundErr();
        }
        
    }
    
    private void removeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtActionPerformed
        removeOperation();
    }//GEN-LAST:event_removeBtActionPerformed

    private void opTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opTfActionPerformed

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        exit();
    }//GEN-LAST:event_closeBtActionPerformed

    public void exit(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Do you really want to exit?",
                "Exit",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){
           dispose();
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDelPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDelPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDelPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDelPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDelOperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBt;
    private javax.swing.JComboBox<String> opCb;
    private javax.swing.JLabel opLb;
    private javax.swing.JTextField opTf;
    private javax.swing.JButton removeBt;
    private javax.swing.JLabel titleTf;
    // End of variables declaration//GEN-END:variables
}
