//João Alberto Benaci Torezan

import javax.swing.JOptionPane;

public class FormEditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form FormEditCustomer
     */
    
    private BDStorage storage = BDStorage.createStorage();
    
    private static FormEditEmployee e;
    
    private FormEditEmployee() {
        initComponents();
    }

    //MÉTODO SINGLETON
    
    public static FormEditEmployee createEditEmployee() {
        if(e == null) {
            e = new FormEditEmployee();
        }
        return e;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTf = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        nameLb = new javax.swing.JLabel();
        newCpfLb = new javax.swing.JLabel();
        newCpfTf = new javax.swing.JTextField();
        phoneLb = new javax.swing.JLabel();
        phoneTf = new javax.swing.JTextField();
        closeBt = new javax.swing.JButton();
        saveBt = new javax.swing.JButton();
        registeredLb = new javax.swing.JLabel();
        registeredCpfLb = new javax.swing.JLabel();
        registeredCpfTf = new javax.swing.JTextField();
        newLb = new javax.swing.JLabel();
        roleTf = new javax.swing.JTextField();
        roleLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee");

        titleTf.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        titleTf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTf.setText("EDIT EMPLOYEE");

        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        nameLb.setText("Name:");

        newCpfLb.setText("CPF:");

        newCpfTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCpfTfActionPerformed(evt);
            }
        });

        phoneLb.setText("Phone:");

        closeBt.setText("Close");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });

        saveBt.setText("Save");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        registeredLb.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        registeredLb.setText("Registered CPF:");

        registeredCpfLb.setText("CPF:");

        registeredCpfTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredCpfTfActionPerformed(evt);
            }
        });

        newLb.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        newLb.setText("New Information:");

        roleTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleTfActionPerformed(evt);
            }
        });

        roleLb.setText("Role:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(registeredCpfLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registeredCpfTf))
                    .addComponent(newLb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registeredLb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(closeBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBt))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLb)
                            .addComponent(phoneLb)
                            .addComponent(newCpfLb)
                            .addComponent(roleLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roleTf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newCpfTf)
                            .addComponent(nameTf)
                            .addComponent(phoneTf, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleTf)
                .addGap(18, 18, 18)
                .addComponent(registeredLb)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registeredCpfLb)
                    .addComponent(registeredCpfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(newLb)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCpfLb)
                    .addComponent(newCpfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLb)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLb)
                    .addComponent(phoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleLb)
                    .addComponent(roleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBt)
                    .addComponent(closeBt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void newCpfTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCpfTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCpfTfActionPerformed

    private void registeredCpfTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredCpfTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredCpfTfActionPerformed

    private void roleTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleTfActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        editEmployee();
    }//GEN-LAST:event_saveBtActionPerformed

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        exit();
    }//GEN-LAST:event_closeBtActionPerformed

    private void cleanTf() {
        nameTf.setText("");
        registeredCpfTf.setText("");
        phoneTf.setText("");
        newCpfTf.setText("");
        roleTf.setText("");
    }
    
    private void editEmployee() {
        try{
            int id = GetArrayId.createGetArrayId().getEmployeeId(registeredCpfTf.getText());
            storage.getEmployees().get(id).setCpf(newCpfTf.getText()); //Reflexividade
            storage.getEmployees().get(id).setName(nameTf.getText()); //Reflexividade
            storage.getEmployees().get(id).setPhone(phoneTf.getText()); //Reflexividade
            
            cleanTf();
        }
        catch(ItemNotFoundExeption infe) {
            infe.itemNotFoundErr();
        }
        catch(DupCpfException dce) {
           dce.DupCpfErr();
        }
    }
    
    public void exit(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Do you really want to exit?",
                "Exit",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){
           dispose();
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel nameLb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel newCpfLb;
    private javax.swing.JTextField newCpfTf;
    private javax.swing.JLabel newLb;
    private javax.swing.JLabel phoneLb;
    private javax.swing.JTextField phoneTf;
    private javax.swing.JLabel registeredCpfLb;
    private javax.swing.JTextField registeredCpfTf;
    private javax.swing.JLabel registeredLb;
    private javax.swing.JLabel roleLb;
    private javax.swing.JTextField roleTf;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel titleTf;
    // End of variables declaration//GEN-END:variables
}
