//Versão do NET BEANS: 25
//João Alberto Benaci Torezan

import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel1 = new javax.swing.JLabel();
        mainLabel2 = new javax.swing.JLabel();
        operationBt = new javax.swing.JButton();
        intrumentsBt = new javax.swing.JButton();
        peopleBt = new javax.swing.JButton();
        exitBt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opMenu = new javax.swing.JMenu();
        opMenuIt = new javax.swing.JMenuItem();
        intrumentsMenuIt = new javax.swing.JMenuItem();
        PeopleMenuIt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management System");

        mainLabel1.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        mainLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel1.setText("INSTRUMENT STORE");

        mainLabel2.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        mainLabel2.setText("MANAGEMENT SYSTEM");

        operationBt.setText("Operation...");
        operationBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationBtActionPerformed(evt);
            }
        });

        intrumentsBt.setText("Instruments...");
        intrumentsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intrumentsBtActionPerformed(evt);
            }
        });

        peopleBt.setText("People...");
        peopleBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleBtActionPerformed(evt);
            }
        });

        exitBt.setText("Close");
        exitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtActionPerformed(evt);
            }
        });

        opMenu.setText("Options");

        opMenuIt.setText("Operation...");
        opMenuIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMenuItActionPerformed(evt);
            }
        });
        opMenu.add(opMenuIt);

        intrumentsMenuIt.setText("Instruments...");
        intrumentsMenuIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intrumentsMenuItActionPerformed(evt);
            }
        });
        opMenu.add(intrumentsMenuIt);

        PeopleMenuIt.setText("People...");
        PeopleMenuIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeopleMenuItActionPerformed(evt);
            }
        });
        opMenu.add(PeopleMenuIt);

        jMenuBar1.add(opMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainLabel2)
                                .addComponent(mainLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(operationBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(intrumentsBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(peopleBt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exitBt)
                        .addGap(14, 14, 14))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mainLabel1, mainLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainLabel2)
                .addGap(18, 18, 18)
                .addComponent(operationBt)
                .addGap(18, 18, 18)
                .addComponent(intrumentsBt)
                .addGap(18, 18, 18)
                .addComponent(peopleBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(exitBt)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operationBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationBtActionPerformed
        FormOperationMenu.createOperationMenu().setVisible(true);
    }//GEN-LAST:event_operationBtActionPerformed

    private void peopleBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleBtActionPerformed
        FormPeopleMenu.createPeopleMenu().setVisible(true);
    }//GEN-LAST:event_peopleBtActionPerformed

    private void intrumentsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intrumentsBtActionPerformed
        FormInstrumentMenu.createInstrumentMenu().setVisible(true);
    }//GEN-LAST:event_intrumentsBtActionPerformed

    private void opMenuItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMenuItActionPerformed
        FormOperationMenu.createOperationMenu().setVisible(true);
    }//GEN-LAST:event_opMenuItActionPerformed

    private void intrumentsMenuItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intrumentsMenuItActionPerformed
        FormInstrumentMenu.createInstrumentMenu().setVisible(true);
    }//GEN-LAST:event_intrumentsMenuItActionPerformed

    private void PeopleMenuItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeopleMenuItActionPerformed
        FormPeopleMenu.createPeopleMenu().setVisible(true);
    }//GEN-LAST:event_PeopleMenuItActionPerformed

    private void exitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtActionPerformed
        exit();
    }//GEN-LAST:event_exitBtActionPerformed

    public void exit(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Do you really want to exit?",
                "Exit",
                JOptionPane.YES_NO_OPTION
        );
        
       if(resp == 0){
           dispose();
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PeopleMenuIt;
    private javax.swing.JButton exitBt;
    private javax.swing.JButton intrumentsBt;
    private javax.swing.JMenuItem intrumentsMenuIt;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel mainLabel1;
    private javax.swing.JLabel mainLabel2;
    private javax.swing.JMenu opMenu;
    private javax.swing.JMenuItem opMenuIt;
    private javax.swing.JButton operationBt;
    private javax.swing.JButton peopleBt;
    // End of variables declaration//GEN-END:variables
}
