/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joao
 */
public class OperationMenu extends javax.swing.JFrame {

    /**
     * Creates new form OperationMenu
     */
    
    private static OperationMenu o;
    
    public OperationMenu() {
        initComponents();
    }
    
    public static OperationMenu createOperationMenu() {
        if(o == null) {
            o = new OperationMenu();
        }
        return o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operationLb = new javax.swing.JLabel();
        operationTf = new javax.swing.JTextField();
        searchBt = new javax.swing.JButton();
        saleCb = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        operationTb = new javax.swing.JTable();
        allOperationLb = new javax.swing.JLabel();
        operationMb = new javax.swing.JMenuBar();
        saleMenu = new javax.swing.JMenu();
        addSale = new javax.swing.JMenuItem();
        delSale = new javax.swing.JMenuItem();
        editSale = new javax.swing.JMenuItem();
        acquisitionMenu = new javax.swing.JMenu();
        addAcquisition = new javax.swing.JMenuItem();
        delAcquisition = new javax.swing.JMenuItem();
        editAcquisition = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        operationLb.setText("Search Operation by Id:");

        operationTf.setText("Insert Operation Id");

        searchBt.setText("Search");

        saleCb.setText("Sale");
        saleCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleCbActionPerformed(evt);
            }
        });

        operationTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(operationTb);

        allOperationLb.setText("All Operations:");

        saleMenu.setText("Sale");

        addSale.setText("Add Sale");
        addSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSaleActionPerformed(evt);
            }
        });
        saleMenu.add(addSale);

        delSale.setText("Remove Sale");
        saleMenu.add(delSale);

        editSale.setText("Edit Sale");
        saleMenu.add(editSale);

        operationMb.add(saleMenu);

        acquisitionMenu.setText("Acquisition");

        addAcquisition.setText("Add Acquisition");
        acquisitionMenu.add(addAcquisition);

        delAcquisition.setText("Remove Acquisition");
        acquisitionMenu.add(delAcquisition);

        editAcquisition.setText("Edit Acquisition");
        acquisitionMenu.add(editAcquisition);

        operationMb.add(acquisitionMenu);

        setJMenuBar(operationMb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allOperationLb)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operationLb)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operationTf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saleCb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBt)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(operationLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBt)
                    .addComponent(saleCb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allOperationLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saleCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleCbActionPerformed

    private void addSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperationMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acquisitionMenu;
    private javax.swing.JMenuItem addAcquisition;
    private javax.swing.JMenuItem addSale;
    private javax.swing.JLabel allOperationLb;
    private javax.swing.JMenuItem delAcquisition;
    private javax.swing.JMenuItem delSale;
    private javax.swing.JMenuItem editAcquisition;
    private javax.swing.JMenuItem editSale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel operationLb;
    private javax.swing.JMenuBar operationMb;
    private javax.swing.JTable operationTb;
    private javax.swing.JTextField operationTf;
    private javax.swing.JCheckBox saleCb;
    private javax.swing.JMenu saleMenu;
    private javax.swing.JButton searchBt;
    // End of variables declaration//GEN-END:variables
}
